name: ci

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Set up Go
        uses: "actions/setup-go@v2"
        with:
          go-version: '1.20'

      - name: Check Go version
        run: go version  

      - name: Checkout repository and submodules
        uses: actions/checkout@v2
      
      - name: Build application
        run: ./scripts/buildprod.sh

      - name: "Migrate Databse (install goose)"
        run: go install github.com/pressly/goose/v3/cmd/goose@latest
      
      - name: "Migrate Databse (migrate)"
        env: 
          DATABASE_URL: '${{ secrets.DATABASE_URL }}'
        run: ./scripts/migrateup.sh
      
      - name: 'auth to GPC with service account'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Use gcloud CLI'
        env:
          IMAGE: 'novelty'
          PROJECT_ID: 'notely-409016'
          REGION: 'us-central1'
          REPOSITORY: 'notely-ar-repo'
        run: gcloud builds submit --tag ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE}:latest .

      - name: "GCP  DEPLOY STEP"
        env:
            IMAGE: 'novelty'
            PROJECT_ID: 'notely-409016'
            REGION: 'us-central1'
            REPOSITORY: 'notely-ar-repo'
        run: gcloud run deploy notely --image ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE}:latest --region ${REGION} --allow-unauthenticated --project $PROJECT_ID --max-instances=1
      



